version: '3.8'

services:
  # Development environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"  # React frontend
      - "8000:8000"  # FastAPI backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # For hot reloading in Docker
    env_file:
      - .env

  # Production environment
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - db-data:/app/data  # For persistent database storage

volumes:
  db-data: